spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${LOCAL_DB_PATH:/app/db_temp/demodb}
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update  # Adjust as needed

artifact-repository:
  path: ${REPOSITORY_PATH:/app/repository/main}